#!/usr/bin/env python3
import re, json
from pathlib import Path

ROOT = Path('/home/gone/.openclaw/workspace')
DROPS = ROOT / 'drops'
OUT = ROOT / 'graplite-scan' / 'output' / 'drops'

IGNORE_DIRS = {'.git','node_modules','build','dist','.dart_tool','.idea','.vscode','.coonie','.graplite','.cache','.wrangler','Pods'}

MANIFESTS = [
  'package.json','pnpm-lock.yaml','yarn.lock','pubspec.yaml','pyproject.toml','requirements.txt',
  'go.mod','Cargo.toml','pom.xml','build.gradle','docker-compose.yml','docker-compose.yaml','Dockerfile',
  '.env.example','README.md','codemagic.yaml','drops_setup.iss'
]

def safe_read(p: Path, max_bytes=200000):
  try:
    data = p.read_bytes()
    if len(data) > max_bytes:
      data = data[:max_bytes]
    return data.decode('utf-8', errors='replace')
  except Exception:
    return ''

def list_tree(base: Path, depth=2):
  lines=[]
  def rec(cur: Path, d: int, prefix=''):
    if d < 0:
      return
    try:
      items = sorted(cur.iterdir(), key=lambda x: (x.is_file(), x.name.lower()))
    except Exception:
      return
    for it in items:
      if it.name in IGNORE_DIRS:
        continue
      if it.is_dir():
        lines.append(f"{prefix}{it.name}/")
        if d > 0:
          rec(it, d-1, prefix+'  ')
      else:
        lines.append(f"{prefix}{it.name}")
  rec(base, depth)
  return lines

def find_files(base: Path, max_depth=4):
  out=[]
  for p in base.rglob('*'):
    if any(part in IGNORE_DIRS for part in p.parts):
      continue
    try:
      rel = p.relative_to(base)
    except Exception:
      continue
    if len(rel.parts) > max_depth:
      continue
    if p.is_file() and p.name in MANIFESTS:
      out.append(rel.as_posix())
  return sorted(set(out))

def detect_stack():
  stacks=[]
  if (DROPS/'app'/'pubspec.yaml').exists():
    stacks.append('Flutter (app/)')
  if (DROPS/'backend'/'package.json').exists():
    stacks.append('Node.js (backend/)')
  if (DROPS/'ExtentionChrome'/'extension'/'package.json').exists():
    stacks.append('Chrome Extension (ExtentionChrome/extension)')
  if (DROPS/'infra').exists():
    stacks.append('Infra scripts/config (infra/)')
  return stacks

def parse_pkg_json(p: Path):
  try:
    return json.loads(p.read_text(encoding='utf-8'))
  except Exception:
    return {}

def collect_commands():
  cmds=[]
  if (DROPS/'package.json').exists():
    root_pkg = parse_pkg_json(DROPS/'package.json')
    if isinstance(root_pkg.get('scripts'), dict) and root_pkg['scripts']:
      cmds.append(('drops/package.json', root_pkg['scripts']))
  if (DROPS/'backend'/'package.json').exists():
    be_pkg = parse_pkg_json(DROPS/'backend'/'package.json')
    if isinstance(be_pkg.get('scripts'), dict) and be_pkg['scripts']:
      cmds.append(('drops/backend/package.json', be_pkg['scripts']))
  return cmds

def heuristic_entrypoints():
  patterns=[
    re.compile(r'\bapp\.listen\(', re.I),
    re.compile(r'\blisten\(', re.I),
    re.compile(r'createServer\(', re.I),
    re.compile(r'Fastify\(', re.I),
    re.compile(r'Express\(', re.I),
    re.compile(r'\bmain\(', re.I),
  ]
  hits=set()
  for ext in ('*.ts','*.js'):
    for p in DROPS.rglob(ext):
      if any(part in IGNORE_DIRS for part in p.parts):
        continue
      txt=safe_read(p, max_bytes=120000)
      if any(pt.search(txt) for pt in patterns):
        hits.add(p.relative_to(DROPS).as_posix())
  return sorted(hits)[:60]

def main():
  OUT.mkdir(parents=True, exist_ok=True)

  stacks = detect_stack()
  manifests = find_files(DROPS, max_depth=4)
  tree_lines = list_tree(DROPS, depth=2)
  commands = collect_commands()
  entry_files = heuristic_entrypoints()

  fast = []
  fast.append('# PROJECT_FAST_MAP — DROPS')
  fast.append('')
  fast.append('_Generated by `graplite-scan` (offline heuristics; SCIP not enabled yet)._')
  fast.append('')
  fast.append('## TL;DR')
  fast.append(f"- Repo root: `{DROPS}`")
  fast.append('- Product: DROPS (file transfer/sharing)')
  fast.append('- Components detected:')
  for s in stacks:
    fast.append(f"  - {s}")
  fast.append('')

  fast.append('## Repo layout (depth≈2)')
  fast.append('```')
  fast.extend(tree_lines[:300])
  fast.append('```')
  fast.append('')

  fast.append('## Key manifests (depth<=4)')
  fast.append('```')
  for m in manifests:
    fast.append(m)
  fast.append('```')
  fast.append('')

  fast.append('## Entrypoints (heuristic candidates)')
  if entry_files:
    fast.append('These files likely contain server/app entrypoints or bootstraps:')
    for f in entry_files:
      fast.append(f"- `{f}`")
  else:
    fast.append('- (No obvious entrypoint hits from simple patterns yet.)')
  fast.append('')

  fast.append('## Run / Build / Test (from package.json scripts)')
  if commands:
    for where, scripts in commands:
      fast.append(f"### {where}")
      for k,v in scripts.items():
        fast.append(f"- `{k}`: `{v}`")
  else:
    fast.append('- (No scripts parsed.)')
  fast.append('')

  fast.append('## Next indexing step (for accurate blast radius)')
  fast.append('- Add SCIP indexing for backend TypeScript/Node to compute:')
  fast.append('  - key symbols by centrality')
  fast.append('  - reference-based blast radius')
  fast.append('- For Flutter/Dart: if no SCIP indexer, fallback to import graph + grep-based heuristics')
  fast.append('')

  (OUT/'PROJECT_FAST_MAP.md').write_text('\n'.join(fast), encoding='utf-8')

  blast=[]
  blast.append('# PROJECT_BLAST_RADIUS — DROPS')
  blast.append('')
  blast.append('_Generated by `graplite-scan` (offline heuristics; SCIP not enabled yet)._')
  blast.append('')
  blast.append('## High-level modules')
  blast.append('- `app/`: Flutter app')
  blast.append('- `backend/`: Node.js backend API + storage integration')
  blast.append('- `ExtentionChrome/extension/`: Chrome extension')
  blast.append('- `infra/`: infra scripts/config')
  blast.append('- `docs/`: project docs and analysis')
  blast.append('')

  blast.append('## Likely high blast-radius areas (heuristic)')
  blast.append('- Backend entry + routing (see FAST_MAP entrypoint candidates)')
  blast.append('- Transfer protocol / signaling / storage integration (backend + app)')
  blast.append('')

  blast.append('## What to verify when changing common areas')
  blast.append('- Backend changes: run unit tests (if present) + API smoke')
  blast.append('- App changes: run `flutter test` (if configured) + build target(s)')
  blast.append('- Protocol changes: test multi-file transfer end-to-end (app + backend)')
  blast.append('')

  blast.append('## Next step to make this report “real”')
  blast.append('- Enable SCIP for backend → compute symbol centrality + reference edges')
  blast.append('- Add `--diff` mode: `git diff` → changed files/symbols → impacted modules')
  blast.append('')

  (OUT/'PROJECT_BLAST_RADIUS.md').write_text('\n'.join(blast), encoding='utf-8')

  print('OK: rendered maps to', OUT)

if __name__ == '__main__':
  main()
