#!/usr/bin/env bash
set -euo pipefail

REPO_PATH="${1:-}"
OUT_DIR="${2:-}"
if [[ -z "$REPO_PATH" || -z "$OUT_DIR" ]]; then
  echo "Usage: scan_repo.sh <repo_path> <out_dir>" >&2
  exit 1
fi

cd "$REPO_PATH"
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$REPO_ROOT"

mkdir -p "$OUT_DIR"

# Basic preflight facts
{
  echo "# Repo Preflight"
  echo
  echo "- scanned_at: $(date -Is)"
  echo "- repo_root: $REPO_ROOT"
  echo "- git_branch: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'n/a')"
  echo "- git_head: $(git rev-parse --short HEAD 2>/dev/null || echo 'n/a')"
  echo "- git_status:"
  git status -sb 2>/dev/null || true
  echo
  echo "## Top-level"
  ls -la
  echo
  echo "## Tree (depth=3)"
  if command -v tree >/dev/null 2>&1; then
    tree -L 3 -a -I '.git|node_modules|build|dist|.dart_tool|.idea|.vscode|.coonie|.graplite|.cache'
  else
    find . -maxdepth 3 -type d -not -path './.git*' | sed -n '1,200p'
  fi
  echo
  echo "## Manifests (depth=4)"
  find . -maxdepth 4 -type f \
    \( -name package.json -o -name pnpm-lock.yaml -o -name yarn.lock -o -name pubspec.yaml \
       -o -name pyproject.toml -o -name requirements.txt -o -name go.mod -o -name Cargo.toml \
       -o -name pom.xml -o -name build.gradle -o -name docker-compose.yml -o -name docker-compose.yaml \
       -o -name Dockerfile -o -name .env.example -o -name README.md \) \
    | sed -n '1,250p'
  echo
  echo "## Entrypoint heuristics"
  if command -v rg >/dev/null 2>&1; then
    rg -n --hidden --no-ignore-vcs \
      -S "\b(main\(|createServer\(|listen\(|run\(|bootstrap\(|init\(|app\.listen\(|Fastify\(|Express\()" \
      -g'!**/.git/**' -g'!**/node_modules/**' -g'!**/build/**' -g'!**/dist/**' -g'!**/.dart_tool/**' \
      | sed -n '1,200p' || true
  else
    echo "rg not installed; skipping"
  fi
} > "$OUT_DIR/PREFLIGHT.md"

# Minimal FAST_MAP draft (template + some auto-filled bits)
{
  echo "# PROJECT_FAST_MAP"
  echo
  echo "_Generated by graplite-scan (local scripts)." 
  echo
  echo "## TL;DR"
  echo "- (fill)"
  echo
  echo "## Repo layout"
  echo "- (fill)"
  echo
  echo "## Entrypoints"
  echo "- (fill)"
  echo
  echo "## Run / Build / Test"
  echo "- (fill)"
} > "$OUT_DIR/PROJECT_FAST_MAP.md"

# Minimal BLAST_RADIUS draft
{
  echo "# PROJECT_BLAST_RADIUS"
  echo
  echo "_Generated by graplite-scan (local scripts)." 
  echo
  echo "## Module graph summary"
  echo "- (fill)"
  echo
  echo "## Top risk nodes"
  echo "- (fill)"
  echo
  echo "## Impact recipes"
  echo "- (fill)"
} > "$OUT_DIR/PROJECT_BLAST_RADIUS.md"

echo "OK: wrote $OUT_DIR/PREFLIGHT.md + templates"
